### ISSUE TITLE
ChannelFinder backend migration to nosql

### ISSUE THREAD

**Issue by shroffk** [epics-rip/ChannelFinderService#1]
As the Channelfinder database expands to approach millions of channel - property/tag elements Nosql databases like mongoDB rise as an attractive alternative.

Preliminary performance comparisons
Databade: 150k channels with 15 million channel-properties / channel-properties
Queries: Based on channel names and property values

Mysql:
![image](https://cloud.githubusercontent.com/assets/2111304/4372359/63e75e00-4323-11e4-9471-3874ad9acebf.png)

MongoDB:
![image](https://cloud.githubusercontent.com/assets/2111304/4372366/7a183dca-4323-11e4-8601-01751b29ef99.png)

**Comment by shroffk** [comment]
- [x] Create channels, tags, properties
- [x] Delete channels, tags, properties
- [x] Add validation #2
- [x] Add update functionality (non destructive - POST) #3 
- [x] Add update functionality (destructive - PUT) #3 
- [x] Add owner checking (authorization)
- [x] Add sorted response
- [x] Optimized Queries #5 
- [x] Cleanup unused classes
- [x] Documentations of new API and installation 
- [x] tags/<tagName>/channel PUT/DELETE
- [x] tags/<propertyName>/channel PUT/DELETE
- [x] transport client / node management

**Comment by ralphlange** [comment]
Have you put this beneath an API?
I.e. can you still use the mySQL backend?
