### ISSUE TITLE
Not able to run scripts in ElasticSearch

### ISSUE THREAD

**Issue by mskinner5278** [epics-rip/ChannelFinderService#10]
must update elasticsearch.yml

**Comment by shroffk** [comment]
The new ChannelFinder service uses scripting for the more complicated requests and therefore requires scripting support to be enabled in elasticsearch.

The following should be added to the elasticsearch.yml used 

```
################################# Scripting ###############################

script.inline: on
script.indexed: on
```

more information can be found here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#enable-dynamic-scripting

you can locate the elasticsearch.yml using the following documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-dir-layout.html
