### ISSUE TITLE
first run

### ISSUE THREAD

**Issue by shengb** [epics-rip/ChannelFinderService#8]
All those are from Yanqing:
elasticsearch: version 1.7.2. 
1. From the web service with raw http: "http://localhost:8080/ChannelFinder/resources/channels". 
This page contains the following errors:
error on line 1 at column 1: Start tag expected.
Below is a rendering of the page up to the first error.
1. javaCFCClient
   the api's jar package was generated. And the "mvn test" all passed. 
   Does this mean that the javaCFClient and the channelfinder service are all OK?
   But why did nothing showup when I visit the following URLs after "mvn test"?
   http://localhost:8080/ChannelFinder/resources/channels
   http://localhost:8080/ChannelFinder/resources/tags
   http://localhost:8080/ChannelFinder/resources/properties

**Comment by shroffk** [comment]
Are you look at the raw data coming from the service?

**Comment by shroffk** [comment]
The first is a client side error message which the browser displays when it gets and empty list

The second behaviour is due to the fact that the unit tests will typically clean up after themselves and remove all the tags and properties they created.
