### ISSUE TITLE
ldap config account password, and python tests' http status

### ISSUE THREAD

**Issue by fedordjia** [epics-rip/ChannelFinderService#9]
To run the python test with the source, the ldap config can't use the ldif file directly. When change the password of ldap's account to non additivity. The test begin to run.

When run the python test. The testcfchannels.py runs OK. Both the testcftags and testcfproperties return failure similar as follow.
"AssertionError: unexpected return code for put operation - expected 204, received 200".
 But the server runs OK with "POST, DELETE, PUT, GET" requests.

**Comment by shroffk** [comment]
Fixed in the elastic search version 3 of channelfinder service
